# Configuration fragment for rotary encoders past the pinky-finger keys.

ports:
  rotary-encoder:
    include: true
    type: custom-cylindroid  # Round threaded shaft.
    size: [7, 7, 3]  # 7 mm diameter.
    alignment:
      segment: 1
    anchoring:
      anchor: m5L1a
      extrinsic-offset: [-1, 10, -1]
      # Rotation here is intended to match both the angle of the thumb cluster
      # on the z axis and the angle of the plate at the anchor point.
      intrinsic-rotation: [0, π/2, 0.12]
    holder:
      include: true
      type: through-hole
