name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install leiningen
      run: sudo apt install leiningen
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
